version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "craftundfun"
    allow:
      - dependency-type: "direct"
    package:
      - name: "mysql-connector-python"
        range: "~=8.1.0"
      - name: "requests"
        range: "~=2.31.0"
      - name: "mutagen"
        range: "~=1.46.0"
      - name: "nest-asyncio"
      - name: "httpx"
        range: "~=0.24.1"
      - name: "discord.py"
        range: "~=2.3.2"
      - name: "gTTS"
        range: "~=2.4.0"
      - name: "python-dateutil"
        range: "~=2.8.2"
