version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"  # Passe das Verzeichnis entsprechend deiner Projektstruktur an
    schedule:
      interval: "daily" # Hier kannst du das Aktualisierungsintervall anpassen
    open-pull-requests-limit: 10
    package-manager: "pip"

  # Konfiguration für das mysql-connector-python-Paket
  - package: name: "mysql-connector-python"
    directory: "/"  # Hier ebenfalls das Verzeichnis anpassen
    schedule:
      interval: "daily" # Aktualisierungsintervall anpassen, falls gewünscht

  # Konfiguration für das requests-Paket
  - package: name: "requests"
    directory: "/"  # Hier ebenfalls das Verzeichnis anpassen
    schedule:
      interval: "daily" # Aktualisierungsintervall anpassen, falls gewünscht

  # Konfiguration für das mutagen-Paket
  - package: name: "mutagen"
    directory: "/"  # Hier ebenfalls das Verzeichnis anpassen
    schedule:
      interval: "daily" # Aktualisierungsintervall anpassen, falls gewünscht

  # Konfiguration für das nest-asyncio-Paket
  - package: name: "nest-asyncio"
    directory: "/"  # Hier ebenfalls das Verzeichnis anpassen
    schedule:
      interval: "daily" # Aktualisierungsintervall anpassen, falls gewünscht

  # Konfiguration für das httpx-Paket
  - package: name: "httpx"
    directory: "/"  # Hier ebenfalls das Verzeichnis anpassen
    schedule:
      interval: "daily" # Aktualisierungsintervall anpassen, falls gewünscht

  # Konfiguration für das discord.py-Paket
  - package: name: "discord.py"
    directory: "/"  # Hier ebenfalls das Verzeichnis anpassen
    schedule:
      interval: "daily" # Aktualisierungsintervall anpassen, falls gewünscht

  # Konfiguration für das gTTS-Paket
  - package: name: "gTTS"
    directory: "/"  # Hier ebenfalls das Verzeichnis anpassen
    schedule:
      interval: "daily" # Aktualisierungsintervall anpassen, falls gewünscht

  # Konfiguration für das python-dateutil-Paket
  - package: name: "python-dateutil"
    directory: "/"  # Hier ebenfalls das Verzeichnis anpassen
    schedule:
      interval: "daily" # Aktualisierungsintervall anpassen, falls gewünscht
