FROM python:3.11-slim

COPY ../requirements.whatsapp.txt requirements.txt
COPY ../WhatsappApi.py .
COPY ../src/Entities ./src/Entities
COPY ../src/Helper/ ./src/Helper
COPY ../src/Manager/DatabaseManager.py ./src/Manager/DatabaseManager.py
COPY ../parameters.env .

RUN pip install -r requirements.txt
RUN mkdir "Logs"

ENV TZ=Europe/Berlin

CMD ["python3", "./WhatsappApi.py"]