USE beta;

START TRANSACTION;

INSERT INTO event (value)
VALUES ('JOIN_VOICE_CHANNEL'),
	('LEAVE_VOICE_CHANNEL'),
	('SWITCH_VOICE_CHANNEL'),
	('START_STREAMING'),
	('STOP_STREAMING'),
	('START_WEBCAM'),
	('STOP_WEBCAM'),
	('MUTE_SELF'),
	('UNMUTE_SELF'),
	('DEAFEN_SELF'),
	('UNDEAFEN_SELF'),
	('MUTE_SERVER'),
	('UNMUTE_SERVER'),
	('DEAFEN_SERVER'),
	('UNDEAFEN_SERVER'),
	('START_ACTIVITY'),
	('STOP_ACTIVITY'),
	('STATUS_ONLINE'),
	('STATUS_IDLE'),
	('STATUS_DND'),
	('STATUS_OFFLINE');

COMMIT;




